services:
  - type: web
    name: pollution-tracker-front
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/tp3_2/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
